polipo:
  image: clue/polipo
  ports:
   - "8123:8123"
  volumes:
   - ./polipo:/etc/polipo

stunnel:
  build: .
  links:
   - polipo
  ports:
   - "465:443"
   - "1080"
  volumes:
   - ./stunnel:/etc/stunnel

